### ISSUE TITLE
Gaussian Blur calculation

### ISSUE THREAD

**Issue by pufik1337** [HPCE/hpce-2017-cw5#2] opened 2017-11-11 12:18 UTC
It seems that the reference execute function of the gaussian blur puzzle only takes into account the first column of the input image:

`          
acc += contrib * pInput->pixels[yIn*pInput->width];
`

Consequently, the output image should be a blurred repetition of the first column - am I missing something here?

**Comment by m8pple** [comment] 2017-11-11 15:25
No, that's a regression on my part - I noticed it and fixed it a couple of days ago,
but when I transferred it into the new repo must have grabbed the old version,
or not copied it over.

Thanks for spotting that, it wasn't intended to be an optimisation opportunity or anything.

**Closed as completed** 2017-11-11 15:27 UTC
